### ISSUE TITLE
camera coordinate difinition

### ISSUE THREAD

**Issue by zdw-qingdao** [hjwdzh/pyRender#1]
I am using your library to render a image form a mesh model. But the rendered image is not right with the camera pose. I want to know the camera coordinate definition an d transformation matrix definition. Thank you!

**Comment by hjwdzh** [comment]
Thank you for your interest.

1. Camera coordinate definition -- Following the CV convention, x-right, y-down, z-forward.
2. Transformation matrix -- If you take a look at our example, cam2world means to transform a point in camera space to world space. World2cam transforms a world space point to camera space.
3. Please be careful when sending the matrices to render -- you need to make sure that your numpy matrix is contiguous in memory (if not np.ascontiguousarray() will help) and with the dtype as float32.

**Comment by eckertzhang** [comment]
@hjwdzh hello, I'm following rendering work about pyrender. Would you please tell me the world coordinate definition? And why it *0.5 when the vertex coordinate (_V = (V * 0.5).astype('float32')_) is loaded in the objloader.py? Thanks for your time.

**Comment by hjwdzh** [comment]
*0.5 is just for shrinking the geometry so that it is fully captured in the camera.

World coordinate is defined by cam2world and the camera space. The camera space can be seen from above.
