### ISSUE TITLE
Light setting

### ISSUE THREAD

**Issue by eckertzhang** [hjwdzh/pyRender#2]
Hello, I am using the pyRender as a mesh renderer, but I don't know how to set the light source. Would you please give me some information about the lignt setting or its default setting? For example, the position of the point light? Thanks!

**Comment by hjwdzh** [comment]
The core library only delivers a rendered image of Face ID and barycentric coordinate for each pixel. If you want to add lights, you need to write additional functions --
1. based on Face ID/barycentric coordinate, compute surface normal for each pixel.
2. based on lighting/camera/normal/face material, compute light intensity.
